=== raml-apis/Parse/schemas/rolePost.json
{
	"type" : "object" ,
	"$schema" : "http://json-schema.org/draft-03/schema" ,
	"required" : false ,
	"properties" : {
		"ACL" : {
			"type" : "object" ,
			"required" : true ,
			"properties" : {
				"*" : {
					"type" : "object" ,
					"required" : true ,
					"properties" : {
						"read" : {
							"type" : "boolean" ,
							"required" : false
						} ,
						"write" : {
							"type" : "boolean" ,
							"required" : false
						}
					}
				}
			}
		} ,
		"name" : {
			"type" : "string" ,
			"required" : true
		} ,
		"roles" : {
			"type" : "object" ,
			"required" : false ,
			"properties" : {
				"__op" : {
					"type" : "string" ,
					"required" : true ,
					"pattern" : "^AddRelation$"
				} ,
				"objects" : {
					"type" : "array" ,
					"required" : true ,
					"items" : {
						"type" : "object" ,
						"required" : false ,
						"properties" : {
							"__type" : {
								"type" : "string" ,
								"required" : true ,
								"pattern" : "^_Role$"
							} ,
							"className" : {
								"type" : "string" ,
								"required" : true
							} ,
							"objectId" : {
								"type" : "string" ,
								"required" : true
							}
						}
					}
				}
			}
		} ,
		"users" : {
			"type" : "object" ,
			"required" : false ,
			"properties" : {
				"__op" : {
					"type" : "string" ,
					"required" : true ,
					"pattern" : "^AddRelation$"
				} ,
				"objects" : {
					"type" : "array" ,
					"required" : true ,
					"items" : {
						"type" : "object" ,
						"required" : false ,
						"properties" : {
							"__type" : {
								"type" : "string" ,
								"required" : true ,
								"pattern" : "^_User$"
							} ,
							"className" : {
								"type" : "string" ,
								"required" : true
							} ,
							"objectId" : {
								"type" : "string" ,
								"required" : true
							}
						}
					}
				}
			}
		}
	},
	"patternProperties" : {
		"^[a-zA-Z0-9_]+$" : {
			"type" : "any" ,
			"required" : false
		}
	} ,
	"additionalProperties" : false
}

=== raml-apis/Parse/examples/rolePost.json
{
	"name" : "Moderators" ,
	"ACL" : {
		"*" : {
			"read" : true
		}
	} ,
	"roles" : {
		"__op" : "AddRelation" ,
		"objects" : [ {
			"__type" : "Pointer" ,
			"className" : "_Role" ,
			"objectId" : "Ed1nuqPvc"
		} ]
	} ,
	"users" : {
		"__op" : "AddRelation" ,
		"objects" : [ {
			"__type" : "Pointer" ,
			"className" : "_User" ,
			"objectId" : "8TOXdXf3tz"
		} ]
	}
}
